# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\qstem.ui'
#
# Created: Tue Sep 17 19:12:19 2013
#      by: pyside-uic 0.2.14 running on PySide 1.1.2
#
# WARNING! All changes made in this file will be lost!

#from PySide import QtCore, QtGui
from pyface.qt import QtCore,QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1086, 965)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.ModelView = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ModelView.sizePolicy().hasHeightForWidth())
        self.ModelView.setSizePolicy(sizePolicy)
        self.ModelView.setObjectName("ModelView")
        self.gridLayout = QtGui.QGridLayout(self.ModelView)
        self.gridLayout.setContentsMargins(-1, 3, -1, -1)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_45 = QtGui.QHBoxLayout()
        self.horizontalLayout_45.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout_45.setObjectName("horizontalLayout_45")
        self.ModelButtons = QtGui.QVBoxLayout()
        self.ModelButtons.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.ModelButtons.setObjectName("ModelButtons")
        self.LoadModel = QtGui.QPushButton(self.ModelView)
        self.LoadModel.setObjectName("LoadModel")
        self.ModelButtons.addWidget(self.LoadModel)
        self.EditModel = QtGui.QPushButton(self.ModelView)
        self.EditModel.setObjectName("EditModel")
        self.ModelButtons.addWidget(self.EditModel)
        self.ModelParams = QtGui.QPushButton(self.ModelView)
        self.ModelParams.setObjectName("ModelParams")
        self.ModelButtons.addWidget(self.ModelParams)
        self.horizontalLayout_45.addLayout(self.ModelButtons)
        self.ViewingFace = QtGui.QGroupBox(self.ModelView)
        self.ViewingFace.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.ViewingFace.setObjectName("ViewingFace")
        self.gridLayout_3 = QtGui.QGridLayout(self.ViewingFace)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.TopViewRadio = QtGui.QRadioButton(self.ViewingFace)
        self.TopViewRadio.setChecked(True)
        self.TopViewRadio.setObjectName("TopViewRadio")
        self.verticalLayout.addWidget(self.TopViewRadio)
        self.FrontViewRadio = QtGui.QRadioButton(self.ViewingFace)
        self.FrontViewRadio.setObjectName("FrontViewRadio")
        self.verticalLayout.addWidget(self.FrontViewRadio)
        self.gridLayout_3.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.horizontalLayout_45.addWidget(self.ViewingFace)
        self.groupBox_2 = QtGui.QGroupBox(self.ModelView)
        self.groupBox_2.setEnabled(False)
        self.groupBox_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.groupBox_2.setCheckable(False)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_12 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.radioButton_6 = QtGui.QRadioButton(self.groupBox_2)
        self.radioButton_6.setChecked(True)
        self.radioButton_6.setObjectName("radioButton_6")
        self.verticalLayout_2.addWidget(self.radioButton_6)
        self.radioButton_7 = QtGui.QRadioButton(self.groupBox_2)
        self.radioButton_7.setObjectName("radioButton_7")
        self.verticalLayout_2.addWidget(self.radioButton_7)
        self.radioButton_8 = QtGui.QRadioButton(self.groupBox_2)
        self.radioButton_8.setObjectName("radioButton_8")
        self.verticalLayout_2.addWidget(self.radioButton_8)
        self.gridLayout_12.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.horizontalLayout_45.addWidget(self.groupBox_2)
        self.gridLayout.addLayout(self.horizontalLayout_45, 1, 0, 1, 1)
        self.plotLayout = QtGui.QVBoxLayout()
        self.plotLayout.setObjectName("plotLayout")
        self.gridLayout.addLayout(self.plotLayout, 0, 0, 1, 1)
        self.groupBox_6 = QtGui.QGroupBox(self.ModelView)
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.gridLayout_13 = QtGui.QGridLayout()
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.groupBox_14 = QtGui.QGroupBox(self.groupBox_6)
        self.groupBox_14.setTitle("")
        self.groupBox_14.setObjectName("groupBox_14")
        self.horizontalLayout_46 = QtGui.QHBoxLayout(self.groupBox_14)
        self.horizontalLayout_46.setObjectName("horizontalLayout_46")
        self.BoxSizeRadio_2 = QtGui.QRadioButton(self.groupBox_14)
        self.BoxSizeRadio_2.setObjectName("BoxSizeRadio_2")
        self.horizontalLayout_46.addWidget(self.BoxSizeRadio_2)
        self.NCellsRadio_2 = QtGui.QRadioButton(self.groupBox_14)
        self.NCellsRadio_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.NCellsRadio_2.setChecked(True)
        self.NCellsRadio_2.setObjectName("NCellsRadio_2")
        self.horizontalLayout_46.addWidget(self.NCellsRadio_2)
        self.gridLayout_13.addWidget(self.groupBox_14, 0, 7, 1, 1)
        self.label_95 = QtGui.QLabel(self.groupBox_6)
        self.label_95.setObjectName("label_95")
        self.gridLayout_13.addWidget(self.label_95, 0, 0, 1, 1)
        self.SampleSizeX_2 = QtGui.QSpinBox(self.groupBox_6)
        self.SampleSizeX_2.setMinimum(1)
        self.SampleSizeX_2.setProperty("value", 1)
        self.SampleSizeX_2.setObjectName("SampleSizeX_2")
        self.gridLayout_13.addWidget(self.SampleSizeX_2, 0, 2, 1, 1)
        self.SizeXLabel_2 = QtGui.QLabel(self.groupBox_6)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.SizeXLabel_2.setFont(font)
        self.SizeXLabel_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.SizeXLabel_2.setObjectName("SizeXLabel_2")
        self.gridLayout_13.addWidget(self.SizeXLabel_2, 0, 1, 1, 1)
        self.SampleSizeY_2 = QtGui.QSpinBox(self.groupBox_6)
        self.SampleSizeY_2.setMinimum(1)
        self.SampleSizeY_2.setObjectName("SampleSizeY_2")
        self.gridLayout_13.addWidget(self.SampleSizeY_2, 0, 4, 1, 1)
        self.SizeZLabel_2 = QtGui.QLabel(self.groupBox_6)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.SizeZLabel_2.setFont(font)
        self.SizeZLabel_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.SizeZLabel_2.setObjectName("SizeZLabel_2")
        self.gridLayout_13.addWidget(self.SizeZLabel_2, 0, 5, 1, 1)
        self.SizeYLabel_2 = QtGui.QLabel(self.groupBox_6)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.SizeYLabel_2.setFont(font)
        self.SizeYLabel_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.SizeYLabel_2.setObjectName("SizeYLabel_2")
        self.gridLayout_13.addWidget(self.SizeYLabel_2, 0, 3, 1, 1)
        self.SampleSizeZ_2 = QtGui.QSpinBox(self.groupBox_6)
        self.SampleSizeZ_2.setMinimum(1)
        self.SampleSizeZ_2.setObjectName("SampleSizeZ_2")
        self.gridLayout_13.addWidget(self.SampleSizeZ_2, 0, 6, 1, 1)
        self.label_97 = QtGui.QLabel(self.groupBox_6)
        self.label_97.setObjectName("label_97")
        self.gridLayout_13.addWidget(self.label_97, 1, 0, 1, 1)
        self.label_99 = QtGui.QLabel(self.groupBox_6)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_99.setFont(font)
        self.label_99.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_99.setObjectName("label_99")
        self.gridLayout_13.addWidget(self.label_99, 1, 1, 1, 1)
        self.SampleTiltX_2 = QtGui.QDoubleSpinBox(self.groupBox_6)
        self.SampleTiltX_2.setObjectName("SampleTiltX_2")
        self.gridLayout_13.addWidget(self.SampleTiltX_2, 1, 2, 1, 1)
        self.label_98 = QtGui.QLabel(self.groupBox_6)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_98.setFont(font)
        self.label_98.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_98.setObjectName("label_98")
        self.gridLayout_13.addWidget(self.label_98, 1, 3, 1, 1)
        self.SampleTiltY_2 = QtGui.QDoubleSpinBox(self.groupBox_6)
        self.SampleTiltY_2.setObjectName("SampleTiltY_2")
        self.gridLayout_13.addWidget(self.SampleTiltY_2, 1, 4, 1, 1)
        self.label_96 = QtGui.QLabel(self.groupBox_6)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_96.setFont(font)
        self.label_96.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_96.setObjectName("label_96")
        self.gridLayout_13.addWidget(self.label_96, 1, 5, 1, 1)
        self.SampleTiltZ_2 = QtGui.QDoubleSpinBox(self.groupBox_6)
        self.SampleTiltZ_2.setObjectName("SampleTiltZ_2")
        self.gridLayout_13.addWidget(self.SampleTiltZ_2, 1, 6, 1, 1)
        self.groupBox_15 = QtGui.QGroupBox(self.groupBox_6)
        self.groupBox_15.setTitle("")
        self.groupBox_15.setObjectName("groupBox_15")
        self.horizontalLayout_44 = QtGui.QHBoxLayout(self.groupBox_15)
        self.horizontalLayout_44.setObjectName("horizontalLayout_44")
        self.SampleTiltDegreesRadio_2 = QtGui.QRadioButton(self.groupBox_15)
        self.SampleTiltDegreesRadio_2.setChecked(True)
        self.SampleTiltDegreesRadio_2.setObjectName("SampleTiltDegreesRadio_2")
        self.horizontalLayout_44.addWidget(self.SampleTiltDegreesRadio_2)
        self.SampleTiltRadiansRadio_2 = QtGui.QRadioButton(self.groupBox_15)
        self.SampleTiltRadiansRadio_2.setObjectName("SampleTiltRadiansRadio_2")
        self.horizontalLayout_44.addWidget(self.SampleTiltRadiansRadio_2)
        self.gridLayout_13.addWidget(self.groupBox_15, 1, 7, 1, 1)
        self.verticalLayout_12.addLayout(self.gridLayout_13)
        self.gridLayout.addWidget(self.groupBox_6, 2, 0, 1, 1)
        self.gridLayout_2.addWidget(self.ModelView, 0, 0, 3, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1086, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuResults = QtGui.QMenu(self.menubar)
        self.menuResults.setObjectName("menuResults")
        self.menuSettings = QtGui.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.SlabDock = QtGui.QDockWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SlabDock.sizePolicy().hasHeightForWidth())
        self.SlabDock.setSizePolicy(sizePolicy)
        self.SlabDock.setFloating(False)
        self.SlabDock.setFeatures(QtGui.QDockWidget.DockWidgetFloatable|QtGui.QDockWidget.DockWidgetMovable)
        self.SlabDock.setObjectName("SlabDock")
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.gridLayout_14 = QtGui.QGridLayout(self.dockWidgetContents)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.gridLayout_8 = QtGui.QGridLayout()
        self.gridLayout_8.setSpacing(4)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_38 = QtGui.QHBoxLayout()
        self.horizontalLayout_38.setObjectName("horizontalLayout_38")
        self.label_86 = QtGui.QLabel(self.dockWidgetContents)
        self.label_86.setWordWrap(True)
        self.label_86.setObjectName("label_86")
        self.horizontalLayout_38.addWidget(self.label_86)
        self.spinBox_2 = QtGui.QSpinBox(self.dockWidgetContents)
        self.spinBox_2.setObjectName("spinBox_2")
        self.horizontalLayout_38.addWidget(self.spinBox_2)
        self.verticalLayout_9.addLayout(self.horizontalLayout_38)
        self.horizontalLayout_39 = QtGui.QHBoxLayout()
        self.horizontalLayout_39.setObjectName("horizontalLayout_39")
        self.label_3 = QtGui.QLabel(self.dockWidgetContents)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_39.addWidget(self.label_3)
        self.doubleSpinBox_11 = QtGui.QDoubleSpinBox(self.dockWidgetContents)
        self.doubleSpinBox_11.setObjectName("doubleSpinBox_11")
        self.horizontalLayout_39.addWidget(self.doubleSpinBox_11)
        self.verticalLayout_9.addLayout(self.horizontalLayout_39)
        self.horizontalLayout_9.addLayout(self.verticalLayout_9)
        self.gridLayout_8.addLayout(self.horizontalLayout_9, 0, 0, 1, 1)
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_40 = QtGui.QHBoxLayout()
        self.horizontalLayout_40.setObjectName("horizontalLayout_40")
        self.label_85 = QtGui.QLabel(self.dockWidgetContents)
        self.label_85.setWordWrap(True)
        self.label_85.setObjectName("label_85")
        self.horizontalLayout_40.addWidget(self.label_85)
        self.doubleSpinBox_10 = QtGui.QDoubleSpinBox(self.dockWidgetContents)
        self.doubleSpinBox_10.setObjectName("doubleSpinBox_10")
        self.horizontalLayout_40.addWidget(self.doubleSpinBox_10)
        self.verticalLayout_10.addLayout(self.horizontalLayout_40)
        self.horizontalLayout_41 = QtGui.QHBoxLayout()
        self.horizontalLayout_41.setObjectName("horizontalLayout_41")
        self.label_87 = QtGui.QLabel(self.dockWidgetContents)
        self.label_87.setObjectName("label_87")
        self.horizontalLayout_41.addWidget(self.label_87)
        self.doubleSpinBox_12 = QtGui.QDoubleSpinBox(self.dockWidgetContents)
        self.doubleSpinBox_12.setObjectName("doubleSpinBox_12")
        self.horizontalLayout_41.addWidget(self.doubleSpinBox_12)
        self.verticalLayout_10.addLayout(self.horizontalLayout_41)
        self.gridLayout_8.addLayout(self.verticalLayout_10, 0, 3, 1, 1)
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_42 = QtGui.QHBoxLayout()
        self.horizontalLayout_42.setObjectName("horizontalLayout_42")
        self.label_4 = QtGui.QLabel(self.dockWidgetContents)
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_42.addWidget(self.label_4)
        self.spinBox_3 = QtGui.QSpinBox(self.dockWidgetContents)
        self.spinBox_3.setObjectName("spinBox_3")
        self.horizontalLayout_42.addWidget(self.spinBox_3)
        self.verticalLayout_11.addLayout(self.horizontalLayout_42)
        self.horizontalLayout_43 = QtGui.QHBoxLayout()
        self.horizontalLayout_43.setObjectName("horizontalLayout_43")
        self.label_88 = QtGui.QLabel(self.dockWidgetContents)
        self.label_88.setObjectName("label_88")
        self.horizontalLayout_43.addWidget(self.label_88)
        self.doubleSpinBox_13 = QtGui.QDoubleSpinBox(self.dockWidgetContents)
        self.doubleSpinBox_13.setObjectName("doubleSpinBox_13")
        self.horizontalLayout_43.addWidget(self.doubleSpinBox_13)
        self.verticalLayout_11.addLayout(self.horizontalLayout_43)
        self.gridLayout_8.addLayout(self.verticalLayout_11, 0, 2, 1, 1)
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.checkBox_3 = QtGui.QCheckBox(self.dockWidgetContents)
        self.checkBox_3.setObjectName("checkBox_3")
        self.verticalLayout_8.addWidget(self.checkBox_3)
        self.checkBox_4 = QtGui.QCheckBox(self.dockWidgetContents)
        self.checkBox_4.setObjectName("checkBox_4")
        self.verticalLayout_8.addWidget(self.checkBox_4)
        self.checkBox_5 = QtGui.QCheckBox(self.dockWidgetContents)
        self.checkBox_5.setObjectName("checkBox_5")
        self.verticalLayout_8.addWidget(self.checkBox_5)
        self.pushButton_7 = QtGui.QPushButton(self.dockWidgetContents)
        self.pushButton_7.setObjectName("pushButton_7")
        self.verticalLayout_8.addWidget(self.pushButton_7)
        self.gridLayout_8.addLayout(self.verticalLayout_8, 0, 4, 1, 1)
        self.gridLayout_14.addLayout(self.gridLayout_8, 0, 0, 1, 1)
        self.SlabDock.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.SlabDock)
        self.DetectorsDock = QtGui.QDockWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DetectorsDock.sizePolicy().hasHeightForWidth())
        self.DetectorsDock.setSizePolicy(sizePolicy)
        self.DetectorsDock.setFeatures(QtGui.QDockWidget.DockWidgetFloatable|QtGui.QDockWidget.DockWidgetMovable)
        self.DetectorsDock.setObjectName("DetectorsDock")
        self.dockWidgetContents_2 = QtGui.QWidget()
        self.dockWidgetContents_2.setObjectName("dockWidgetContents_2")
        self.gridLayout_15 = QtGui.QGridLayout(self.dockWidgetContents_2)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.tabWidget = QtGui.QTabWidget(self.dockWidgetContents_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.Detector1 = QtGui.QWidget()
        self.Detector1.setObjectName("Detector1")
        self.gridLayout_18 = QtGui.QGridLayout(self.Detector1)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.gridLayout_10 = QtGui.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.gridLayout_9 = QtGui.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_89 = QtGui.QLabel(self.Detector1)
        self.label_89.setObjectName("label_89")
        self.gridLayout_9.addWidget(self.label_89, 0, 0, 1, 2)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_94 = QtGui.QLabel(self.Detector1)
        self.label_94.setObjectName("label_94")
        self.horizontalLayout_8.addWidget(self.label_94)
        self.DetectorInnerAngle = QtGui.QSpinBox(self.Detector1)
        self.DetectorInnerAngle.setObjectName("DetectorInnerAngle")
        self.horizontalLayout_8.addWidget(self.DetectorInnerAngle)
        self.gridLayout_9.addLayout(self.horizontalLayout_8, 1, 0, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_93 = QtGui.QLabel(self.Detector1)
        self.label_93.setObjectName("label_93")
        self.horizontalLayout_4.addWidget(self.label_93)
        self.DetectorOuterAngle = QtGui.QSpinBox(self.Detector1)
        self.DetectorOuterAngle.setObjectName("DetectorOuterAngle")
        self.horizontalLayout_4.addWidget(self.DetectorOuterAngle)
        self.gridLayout_9.addLayout(self.horizontalLayout_4, 1, 1, 1, 2)
        self.label_90 = QtGui.QLabel(self.Detector1)
        self.label_90.setObjectName("label_90")
        self.gridLayout_9.addWidget(self.label_90, 2, 0, 1, 2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_91 = QtGui.QLabel(self.Detector1)
        self.label_91.setObjectName("label_91")
        self.horizontalLayout.addWidget(self.label_91)
        self.DetectorOffsetX = QtGui.QSpinBox(self.Detector1)
        self.DetectorOffsetX.setObjectName("DetectorOffsetX")
        self.horizontalLayout.addWidget(self.DetectorOffsetX)
        self.gridLayout_9.addLayout(self.horizontalLayout, 3, 0, 1, 2)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_92 = QtGui.QLabel(self.Detector1)
        self.label_92.setObjectName("label_92")
        self.horizontalLayout_2.addWidget(self.label_92)
        self.DetectorOffsetY = QtGui.QSpinBox(self.Detector1)
        self.DetectorOffsetY.setObjectName("DetectorOffsetY")
        self.horizontalLayout_2.addWidget(self.DetectorOffsetY)
        self.gridLayout_9.addLayout(self.horizontalLayout_2, 3, 2, 1, 1)
        self.pushButton_8 = QtGui.QPushButton(self.Detector1)
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout_9.addWidget(self.pushButton_8, 4, 0, 1, 1)
        self.pushButton_9 = QtGui.QPushButton(self.Detector1)
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout_9.addWidget(self.pushButton_9, 4, 2, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_9, 0, 0, 1, 1)
        self.gridLayout_18.addLayout(self.gridLayout_10, 0, 0, 1, 1)
        self.tabWidget.addTab(self.Detector1, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout_15.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.DetectorsDock.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.DetectorsDock)
        self.MicroscopeDock = QtGui.QDockWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MicroscopeDock.sizePolicy().hasHeightForWidth())
        self.MicroscopeDock.setSizePolicy(sizePolicy)
        self.MicroscopeDock.setFeatures(QtGui.QDockWidget.DockWidgetFloatable|QtGui.QDockWidget.DockWidgetMovable)
        self.MicroscopeDock.setObjectName("MicroscopeDock")
        self.dockWidgetContents_3 = QtGui.QWidget()
        self.dockWidgetContents_3.setObjectName("dockWidgetContents_3")
        self.gridLayout_16 = QtGui.QGridLayout(self.dockWidgetContents_3)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.MicroscopeConfig = QtGui.QGroupBox(self.dockWidgetContents_3)
        self.MicroscopeConfig.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.MicroscopeConfig.setObjectName("MicroscopeConfig")
        self.gridLayout_4 = QtGui.QGridLayout(self.MicroscopeConfig)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_33 = QtGui.QLabel(self.MicroscopeConfig)
        self.label_33.setObjectName("label_33")
        self.gridLayout_4.addWidget(self.label_33, 0, 3, 1, 1)
        self.label_34 = QtGui.QLabel(self.MicroscopeConfig)
        self.label_34.setObjectName("label_34")
        self.gridLayout_4.addWidget(self.label_34, 1, 3, 1, 1)
        self.label_35 = QtGui.QLabel(self.MicroscopeConfig)
        self.label_35.setObjectName("label_35")
        self.gridLayout_4.addWidget(self.label_35, 2, 3, 1, 1)
        self.label_36 = QtGui.QLabel(self.MicroscopeConfig)
        self.label_36.setObjectName("label_36")
        self.gridLayout_4.addWidget(self.label_36, 3, 3, 1, 1)
        self.label_37 = QtGui.QLabel(self.MicroscopeConfig)
        self.label_37.setObjectName("label_37")
        self.gridLayout_4.addWidget(self.label_37, 4, 3, 1, 1)
        self.label_38 = QtGui.QLabel(self.MicroscopeConfig)
        self.label_38.setObjectName("label_38")
        self.gridLayout_4.addWidget(self.label_38, 5, 3, 1, 1)
        self.label_39 = QtGui.QLabel(self.MicroscopeConfig)
        self.label_39.setObjectName("label_39")
        self.gridLayout_4.addWidget(self.label_39, 6, 3, 1, 1)
        self.label_40 = QtGui.QLabel(self.MicroscopeConfig)
        self.label_40.setObjectName("label_40")
        self.gridLayout_4.addWidget(self.label_40, 8, 3, 1, 1)
        self.label_41 = QtGui.QLabel(self.MicroscopeConfig)
        self.label_41.setObjectName("label_41")
        self.gridLayout_4.addWidget(self.label_41, 0, 5, 1, 1)
        self.label_42 = QtGui.QLabel(self.MicroscopeConfig)
        self.label_42.setObjectName("label_42")
        self.gridLayout_4.addWidget(self.label_42, 1, 5, 1, 1)
        self.label_43 = QtGui.QLabel(self.MicroscopeConfig)
        self.label_43.setObjectName("label_43")
        self.gridLayout_4.addWidget(self.label_43, 2, 5, 1, 1)
        self.label_44 = QtGui.QLabel(self.MicroscopeConfig)
        self.label_44.setObjectName("label_44")
        self.gridLayout_4.addWidget(self.label_44, 3, 5, 1, 1)
        self.label_45 = QtGui.QLabel(self.MicroscopeConfig)
        self.label_45.setObjectName("label_45")
        self.gridLayout_4.addWidget(self.label_45, 4, 5, 1, 1)
        self.label_46 = QtGui.QLabel(self.MicroscopeConfig)
        self.label_46.setObjectName("label_46")
        self.gridLayout_4.addWidget(self.label_46, 5, 5, 1, 1)
        self.label_47 = QtGui.QLabel(self.MicroscopeConfig)
        self.label_47.setObjectName("label_47")
        self.gridLayout_4.addWidget(self.label_47, 6, 5, 1, 1)
        self.label_48 = QtGui.QLabel(self.MicroscopeConfig)
        self.label_48.setObjectName("label_48")
        self.gridLayout_4.addWidget(self.label_48, 9, 5, 1, 1)
        self.label_49 = QtGui.QLabel(self.MicroscopeConfig)
        self.label_49.setObjectName("label_49")
        self.gridLayout_4.addWidget(self.label_49, 9, 3, 1, 1)
        self.label_50 = QtGui.QLabel(self.MicroscopeConfig)
        self.label_50.setObjectName("label_50")
        self.gridLayout_4.addWidget(self.label_50, 10, 3, 1, 1)
        self.label_51 = QtGui.QLabel(self.MicroscopeConfig)
        self.label_51.setObjectName("label_51")
        self.gridLayout_4.addWidget(self.label_51, 10, 5, 1, 1)
        self.pushButton_5 = QtGui.QPushButton(self.MicroscopeConfig)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_4.addWidget(self.pushButton_5, 1, 7, 1, 1)
        self.Cs = QtGui.QDoubleSpinBox(self.MicroscopeConfig)
        self.Cs.setMaximum(200000.0)
        self.Cs.setProperty("value", 1.5)
        self.Cs.setObjectName("Cs")
        self.gridLayout_4.addWidget(self.Cs, 3, 4, 1, 1)
        self.horizontalLayout_23 = QtGui.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_52 = QtGui.QLabel(self.MicroscopeConfig)
        self.label_52.setObjectName("label_52")
        self.horizontalLayout_23.addWidget(self.label_52)
        self.AstigmatismAngle = QtGui.QDoubleSpinBox(self.MicroscopeConfig)
        self.AstigmatismAngle.setObjectName("AstigmatismAngle")
        self.horizontalLayout_23.addWidget(self.AstigmatismAngle)
        self.label_53 = QtGui.QLabel(self.MicroscopeConfig)
        self.label_53.setObjectName("label_53")
        self.horizontalLayout_23.addWidget(self.label_53)
        self.gridLayout_4.addLayout(self.horizontalLayout_23, 2, 7, 1, 1)
        self.pushButton_6 = QtGui.QPushButton(self.MicroscopeConfig)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_4.addWidget(self.pushButton_6, 3, 7, 1, 1)
        self.horizontalLayout_24 = QtGui.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.TDSCheck = QtGui.QCheckBox(self.MicroscopeConfig)
        self.TDSCheck.setChecked(False)
        self.TDSCheck.setObjectName("TDSCheck")
        self.horizontalLayout_24.addWidget(self.TDSCheck)
        self.label_54 = QtGui.QLabel(self.MicroscopeConfig)
        self.label_54.setObjectName("label_54")
        self.horizontalLayout_24.addWidget(self.label_54)
        self.TDSRuns = QtGui.QSpinBox(self.MicroscopeConfig)
        self.TDSRuns.setEnabled(False)
        self.TDSRuns.setMaximum(30000)
        self.TDSRuns.setProperty("value", 30)
        self.TDSRuns.setObjectName("TDSRuns")
        self.horizontalLayout_24.addWidget(self.TDSRuns)
        self.gridLayout_4.addLayout(self.horizontalLayout_24, 4, 7, 1, 1)
        self.horizontalLayout_25 = QtGui.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label_55 = QtGui.QLabel(self.MicroscopeConfig)
        self.label_55.setObjectName("label_55")
        self.horizontalLayout_25.addWidget(self.label_55)
        self.EnergySpread = QtGui.QDoubleSpinBox(self.MicroscopeConfig)
        self.EnergySpread.setProperty("value", 0.3)
        self.EnergySpread.setObjectName("EnergySpread")
        self.horizontalLayout_25.addWidget(self.EnergySpread)
        self.label_56 = QtGui.QLabel(self.MicroscopeConfig)
        self.label_56.setObjectName("label_56")
        self.horizontalLayout_25.addWidget(self.label_56)
        self.gridLayout_4.addLayout(self.horizontalLayout_25, 5, 7, 1, 1)
        self.horizontalLayout_26 = QtGui.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.label_57 = QtGui.QLabel(self.MicroscopeConfig)
        self.label_57.setObjectName("label_57")
        self.horizontalLayout_26.addWidget(self.label_57)
        self.BeamTiltX = QtGui.QDoubleSpinBox(self.MicroscopeConfig)
        self.BeamTiltX.setObjectName("BeamTiltX")
        self.horizontalLayout_26.addWidget(self.BeamTiltX)
        self.label_58 = QtGui.QLabel(self.MicroscopeConfig)
        self.label_58.setObjectName("label_58")
        self.horizontalLayout_26.addWidget(self.label_58)
        self.gridLayout_4.addLayout(self.horizontalLayout_26, 8, 4, 1, 1)
        self.horizontalLayout_27 = QtGui.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.label_59 = QtGui.QLabel(self.MicroscopeConfig)
        self.label_59.setObjectName("label_59")
        self.horizontalLayout_27.addWidget(self.label_59)
        self.BeamTiltY = QtGui.QDoubleSpinBox(self.MicroscopeConfig)
        self.BeamTiltY.setObjectName("BeamTiltY")
        self.horizontalLayout_27.addWidget(self.BeamTiltY)
        self.label_60 = QtGui.QLabel(self.MicroscopeConfig)
        self.label_60.setObjectName("label_60")
        self.horizontalLayout_27.addWidget(self.label_60)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_27.addItem(spacerItem)
        self.gridLayout_4.addLayout(self.horizontalLayout_27, 8, 7, 1, 1)
        self.horizontalLayout_28 = QtGui.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_28.addItem(spacerItem1)
        self.checkBox_2 = QtGui.QCheckBox(self.MicroscopeConfig)
        self.checkBox_2.setObjectName("checkBox_2")
        self.horizontalLayout_28.addWidget(self.checkBox_2)
        self.gridLayout_4.addLayout(self.horizontalLayout_28, 9, 7, 1, 1)
        self.comboBox_2 = QtGui.QComboBox(self.MicroscopeConfig)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.gridLayout_4.addWidget(self.comboBox_2, 0, 7, 1, 1)
        self.Brightness = QtGui.QDoubleSpinBox(self.MicroscopeConfig)
        self.Brightness.setMaximum(1000000.0)
        self.Brightness.setProperty("value", 1.0)
        self.Brightness.setObjectName("Brightness")
        self.gridLayout_4.addWidget(self.Brightness, 9, 4, 1, 1)
        self.DwellTime = QtGui.QDoubleSpinBox(self.MicroscopeConfig)
        self.DwellTime.setMaximum(100000.0)
        self.DwellTime.setProperty("value", 30.0)
        self.DwellTime.setObjectName("DwellTime")
        self.gridLayout_4.addWidget(self.DwellTime, 10, 4, 1, 1)
        self.Temperature = QtGui.QDoubleSpinBox(self.MicroscopeConfig)
        self.Temperature.setObjectName("Temperature")
        self.gridLayout_4.addWidget(self.Temperature, 4, 4, 1, 1)
        self.Cc = QtGui.QDoubleSpinBox(self.MicroscopeConfig)
        self.Cc.setObjectName("Cc")
        self.gridLayout_4.addWidget(self.Cc, 5, 4, 1, 1)
        self.Defocus = QtGui.QDoubleSpinBox(self.MicroscopeConfig)
        self.Defocus.setObjectName("Defocus")
        self.gridLayout_4.addWidget(self.Defocus, 1, 4, 1, 1)
        self.Voltage = QtGui.QDoubleSpinBox(self.MicroscopeConfig)
        self.Voltage.setMaximum(200000.0)
        self.Voltage.setProperty("value", 200.0)
        self.Voltage.setObjectName("Voltage")
        self.gridLayout_4.addWidget(self.Voltage, 0, 4, 1, 1)
        self.Astigmatism = QtGui.QDoubleSpinBox(self.MicroscopeConfig)
        self.Astigmatism.setObjectName("Astigmatism")
        self.gridLayout_4.addWidget(self.Astigmatism, 2, 4, 1, 1)
        self.ConvergenceAngle = QtGui.QDoubleSpinBox(self.MicroscopeConfig)
        self.ConvergenceAngle.setMaximum(300.0)
        self.ConvergenceAngle.setProperty("value", 15.0)
        self.ConvergenceAngle.setObjectName("ConvergenceAngle")
        self.gridLayout_4.addWidget(self.ConvergenceAngle, 6, 4, 1, 1)
        self.gridLayout_16.addWidget(self.MicroscopeConfig, 0, 0, 1, 1)
        self.MicroscopeDock.setWidget(self.dockWidgetContents_3)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.MicroscopeDock)
        self.ProbeDock = QtGui.QDockWidget(MainWindow)
        self.ProbeDock.setFeatures(QtGui.QDockWidget.DockWidgetFloatable|QtGui.QDockWidget.DockWidgetMovable)
        self.ProbeDock.setObjectName("ProbeDock")
        self.dockWidgetContents_4 = QtGui.QWidget()
        self.dockWidgetContents_4.setObjectName("dockWidgetContents_4")
        self.gridLayout_17 = QtGui.QGridLayout(self.dockWidgetContents_4)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label = QtGui.QLabel(self.dockWidgetContents_4)
        self.label.setObjectName("label")
        self.horizontalLayout_6.addWidget(self.label)
        self.comboBox = QtGui.QComboBox(self.dockWidgetContents_4)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_6.addWidget(self.comboBox)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        self.stackedWidget = QtGui.QStackedWidget(self.dockWidgetContents_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setSizeIncrement(QtCore.QSize(1, 1))
        self.stackedWidget.setObjectName("stackedWidget")
        self.STEM = QtGui.QWidget()
        self.STEM.setObjectName("STEM")
        self.gridLayout_22 = QtGui.QGridLayout(self.STEM)
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.groupBox = QtGui.QGroupBox(self.STEM)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_19 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_11.addWidget(self.label_5)
        self.doubleSpinBox = QtGui.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.horizontalLayout_11.addWidget(self.doubleSpinBox)
        self.label_11 = QtGui.QLabel(self.groupBox)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_11.addWidget(self.label_11)
        self.doubleSpinBox_2 = QtGui.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.horizontalLayout_11.addWidget(self.doubleSpinBox_2)
        self.label_10 = QtGui.QLabel(self.groupBox)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_11.addWidget(self.label_10)
        self.spinBox_4 = QtGui.QSpinBox(self.groupBox)
        self.spinBox_4.setObjectName("spinBox_4")
        self.horizontalLayout_11.addWidget(self.spinBox_4)
        self.verticalLayout_7.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_12 = QtGui.QLabel(self.groupBox)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_12.addWidget(self.label_12)
        self.doubleSpinBox_3 = QtGui.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox_3.setObjectName("doubleSpinBox_3")
        self.horizontalLayout_12.addWidget(self.doubleSpinBox_3)
        self.label_13 = QtGui.QLabel(self.groupBox)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_12.addWidget(self.label_13)
        self.doubleSpinBox_4 = QtGui.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox_4.setObjectName("doubleSpinBox_4")
        self.horizontalLayout_12.addWidget(self.doubleSpinBox_4)
        self.label_18 = QtGui.QLabel(self.groupBox)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_12.addWidget(self.label_18)
        self.spinBox_5 = QtGui.QSpinBox(self.groupBox)
        self.spinBox_5.setObjectName("spinBox_5")
        self.horizontalLayout_12.addWidget(self.spinBox_5)
        self.verticalLayout_7.addLayout(self.horizontalLayout_12)
        self.gridLayout_19.addLayout(self.verticalLayout_7, 0, 0, 1, 1)
        self.gridLayout_22.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_5 = QtGui.QGroupBox(self.STEM)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_5.sizePolicy().hasHeightForWidth())
        self.groupBox_5.setSizePolicy(sizePolicy)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox_5)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_21 = QtGui.QLabel(self.groupBox_5)
        self.label_21.setObjectName("label_21")
        self.gridLayout_5.addWidget(self.label_21, 0, 0, 1, 1)
        self.label_24 = QtGui.QLabel(self.groupBox_5)
        self.label_24.setObjectName("label_24")
        self.gridLayout_5.addWidget(self.label_24, 1, 0, 1, 1)
        self.label_27 = QtGui.QLabel(self.groupBox_5)
        self.label_27.setObjectName("label_27")
        self.gridLayout_5.addWidget(self.label_27, 2, 0, 1, 1)
        self.label_30 = QtGui.QLabel(self.groupBox_5)
        self.label_30.setObjectName("label_30")
        self.gridLayout_5.addWidget(self.label_30, 3, 0, 1, 1)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.spinBox_12 = QtGui.QSpinBox(self.groupBox_5)
        self.spinBox_12.setObjectName("spinBox_12")
        self.horizontalLayout_19.addWidget(self.spinBox_12)
        self.label_28 = QtGui.QLabel(self.groupBox_5)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_19.addWidget(self.label_28)
        self.spinBox_13 = QtGui.QSpinBox(self.groupBox_5)
        self.spinBox_13.setObjectName("spinBox_13")
        self.horizontalLayout_19.addWidget(self.spinBox_13)
        self.label_29 = QtGui.QLabel(self.groupBox_5)
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_19.addWidget(self.label_29)
        self.gridLayout_5.addLayout(self.horizontalLayout_19, 2, 2, 1, 1)
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.spinBox_25 = QtGui.QSpinBox(self.groupBox_5)
        self.spinBox_25.setObjectName("spinBox_25")
        self.horizontalLayout_20.addWidget(self.spinBox_25)
        self.label_61 = QtGui.QLabel(self.groupBox_5)
        self.label_61.setObjectName("label_61")
        self.horizontalLayout_20.addWidget(self.label_61)
        self.spinBox_26 = QtGui.QSpinBox(self.groupBox_5)
        self.spinBox_26.setObjectName("spinBox_26")
        self.horizontalLayout_20.addWidget(self.spinBox_26)
        self.label_62 = QtGui.QLabel(self.groupBox_5)
        self.label_62.setObjectName("label_62")
        self.horizontalLayout_20.addWidget(self.label_62)
        self.gridLayout_5.addLayout(self.horizontalLayout_20, 0, 2, 1, 1)
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.spinBox_27 = QtGui.QSpinBox(self.groupBox_5)
        self.spinBox_27.setObjectName("spinBox_27")
        self.horizontalLayout_21.addWidget(self.spinBox_27)
        self.label_63 = QtGui.QLabel(self.groupBox_5)
        self.label_63.setObjectName("label_63")
        self.horizontalLayout_21.addWidget(self.label_63)
        self.spinBox_28 = QtGui.QSpinBox(self.groupBox_5)
        self.spinBox_28.setObjectName("spinBox_28")
        self.horizontalLayout_21.addWidget(self.spinBox_28)
        self.label_64 = QtGui.QLabel(self.groupBox_5)
        self.label_64.setObjectName("label_64")
        self.horizontalLayout_21.addWidget(self.label_64)
        self.gridLayout_5.addLayout(self.horizontalLayout_21, 1, 2, 1, 1)
        self.horizontalLayout_29 = QtGui.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.spinBox_29 = QtGui.QSpinBox(self.groupBox_5)
        self.spinBox_29.setReadOnly(True)
        self.spinBox_29.setObjectName("spinBox_29")
        self.horizontalLayout_29.addWidget(self.spinBox_29)
        self.label_65 = QtGui.QLabel(self.groupBox_5)
        self.label_65.setObjectName("label_65")
        self.horizontalLayout_29.addWidget(self.label_65)
        self.spinBox_30 = QtGui.QSpinBox(self.groupBox_5)
        self.spinBox_30.setObjectName("spinBox_30")
        self.horizontalLayout_29.addWidget(self.spinBox_30)
        self.label_66 = QtGui.QLabel(self.groupBox_5)
        self.label_66.setObjectName("label_66")
        self.horizontalLayout_29.addWidget(self.label_66)
        self.gridLayout_5.addLayout(self.horizontalLayout_29, 3, 2, 1, 1)
        self.gridLayout_22.addWidget(self.groupBox_5, 0, 1, 1, 1)
        self.stackedWidget.addWidget(self.STEM)
        self.TEM = QtGui.QWidget()
        self.TEM.setObjectName("TEM")
        self.gridLayout_21 = QtGui.QGridLayout(self.TEM)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.groupBox_9 = QtGui.QGroupBox(self.TEM)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_9.sizePolicy().hasHeightForWidth())
        self.groupBox_9.setSizePolicy(sizePolicy)
        self.groupBox_9.setObjectName("groupBox_9")
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBox_9)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_22 = QtGui.QLabel(self.groupBox_9)
        self.label_22.setObjectName("label_22")
        self.gridLayout_6.addWidget(self.label_22, 0, 0, 1, 1)
        self.label_25 = QtGui.QLabel(self.groupBox_9)
        self.label_25.setObjectName("label_25")
        self.gridLayout_6.addWidget(self.label_25, 1, 0, 1, 1)
        self.label_31 = QtGui.QLabel(self.groupBox_9)
        self.label_31.setObjectName("label_31")
        self.gridLayout_6.addWidget(self.label_31, 2, 0, 1, 1)
        self.label_32 = QtGui.QLabel(self.groupBox_9)
        self.label_32.setObjectName("label_32")
        self.gridLayout_6.addWidget(self.label_32, 3, 0, 1, 1)
        self.horizontalLayout_22 = QtGui.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.spinBox_14 = QtGui.QSpinBox(self.groupBox_9)
        self.spinBox_14.setReadOnly(True)
        self.spinBox_14.setObjectName("spinBox_14")
        self.horizontalLayout_22.addWidget(self.spinBox_14)
        self.label_67 = QtGui.QLabel(self.groupBox_9)
        self.label_67.setObjectName("label_67")
        self.horizontalLayout_22.addWidget(self.label_67)
        self.spinBox_15 = QtGui.QSpinBox(self.groupBox_9)
        self.spinBox_15.setReadOnly(True)
        self.spinBox_15.setObjectName("spinBox_15")
        self.horizontalLayout_22.addWidget(self.spinBox_15)
        self.label_68 = QtGui.QLabel(self.groupBox_9)
        self.label_68.setObjectName("label_68")
        self.horizontalLayout_22.addWidget(self.label_68)
        self.gridLayout_6.addLayout(self.horizontalLayout_22, 2, 2, 1, 1)
        self.horizontalLayout_30 = QtGui.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.spinBox_31 = QtGui.QSpinBox(self.groupBox_9)
        self.spinBox_31.setObjectName("spinBox_31")
        self.horizontalLayout_30.addWidget(self.spinBox_31)
        self.label_69 = QtGui.QLabel(self.groupBox_9)
        self.label_69.setObjectName("label_69")
        self.horizontalLayout_30.addWidget(self.label_69)
        self.spinBox_32 = QtGui.QSpinBox(self.groupBox_9)
        self.spinBox_32.setObjectName("spinBox_32")
        self.horizontalLayout_30.addWidget(self.spinBox_32)
        self.label_70 = QtGui.QLabel(self.groupBox_9)
        self.label_70.setObjectName("label_70")
        self.horizontalLayout_30.addWidget(self.label_70)
        self.gridLayout_6.addLayout(self.horizontalLayout_30, 0, 2, 1, 1)
        self.horizontalLayout_31 = QtGui.QHBoxLayout()
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.spinBox_33 = QtGui.QSpinBox(self.groupBox_9)
        self.spinBox_33.setReadOnly(True)
        self.spinBox_33.setObjectName("spinBox_33")
        self.horizontalLayout_31.addWidget(self.spinBox_33)
        self.label_71 = QtGui.QLabel(self.groupBox_9)
        self.label_71.setObjectName("label_71")
        self.horizontalLayout_31.addWidget(self.label_71)
        self.spinBox_34 = QtGui.QSpinBox(self.groupBox_9)
        self.spinBox_34.setReadOnly(True)
        self.spinBox_34.setObjectName("spinBox_34")
        self.horizontalLayout_31.addWidget(self.spinBox_34)
        self.label_72 = QtGui.QLabel(self.groupBox_9)
        self.label_72.setObjectName("label_72")
        self.horizontalLayout_31.addWidget(self.label_72)
        self.gridLayout_6.addLayout(self.horizontalLayout_31, 1, 2, 1, 1)
        self.horizontalLayout_32 = QtGui.QHBoxLayout()
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.spinBox_35 = QtGui.QSpinBox(self.groupBox_9)
        self.spinBox_35.setReadOnly(True)
        self.spinBox_35.setObjectName("spinBox_35")
        self.horizontalLayout_32.addWidget(self.spinBox_35)
        self.label_73 = QtGui.QLabel(self.groupBox_9)
        self.label_73.setObjectName("label_73")
        self.horizontalLayout_32.addWidget(self.label_73)
        self.spinBox_36 = QtGui.QSpinBox(self.groupBox_9)
        self.spinBox_36.setReadOnly(True)
        self.spinBox_36.setObjectName("spinBox_36")
        self.horizontalLayout_32.addWidget(self.spinBox_36)
        self.label_74 = QtGui.QLabel(self.groupBox_9)
        self.label_74.setObjectName("label_74")
        self.horizontalLayout_32.addWidget(self.label_74)
        self.gridLayout_6.addLayout(self.horizontalLayout_32, 3, 2, 1, 1)
        self.gridLayout_21.addWidget(self.groupBox_9, 0, 0, 1, 1)
        self.pushButton_4 = QtGui.QPushButton(self.TEM)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_21.addWidget(self.pushButton_4, 0, 1, 1, 1)
        self.stackedWidget.addWidget(self.TEM)
        self.CBED = QtGui.QWidget()
        self.CBED.setObjectName("CBED")
        self.gridLayout_11 = QtGui.QGridLayout(self.CBED)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.groupBox_8 = QtGui.QGroupBox(self.CBED)
        self.groupBox_8.setObjectName("groupBox_8")
        self.gridLayout_20 = QtGui.QGridLayout(self.groupBox_8)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_19 = QtGui.QLabel(self.groupBox_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_16.addWidget(self.label_19)
        self.spinBox_6 = QtGui.QSpinBox(self.groupBox_8)
        self.spinBox_6.setObjectName("spinBox_6")
        self.horizontalLayout_16.addWidget(self.spinBox_6)
        self.label_20 = QtGui.QLabel(self.groupBox_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_16.addWidget(self.label_20)
        self.spinBox_7 = QtGui.QSpinBox(self.groupBox_8)
        self.spinBox_7.setObjectName("spinBox_7")
        self.horizontalLayout_16.addWidget(self.spinBox_7)
        self.gridLayout_20.addLayout(self.horizontalLayout_16, 0, 0, 1, 1)
        self.gridLayout_11.addWidget(self.groupBox_8, 0, 0, 1, 1)
        self.groupBox_10 = QtGui.QGroupBox(self.CBED)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_10.sizePolicy().hasHeightForWidth())
        self.groupBox_10.setSizePolicy(sizePolicy)
        self.groupBox_10.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.groupBox_10.setObjectName("groupBox_10")
        self.gridLayout_7 = QtGui.QGridLayout(self.groupBox_10)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_23 = QtGui.QLabel(self.groupBox_10)
        self.label_23.setObjectName("label_23")
        self.gridLayout_7.addWidget(self.label_23, 0, 0, 1, 1)
        self.label_26 = QtGui.QLabel(self.groupBox_10)
        self.label_26.setObjectName("label_26")
        self.gridLayout_7.addWidget(self.label_26, 1, 0, 1, 1)
        self.label_75 = QtGui.QLabel(self.groupBox_10)
        self.label_75.setObjectName("label_75")
        self.gridLayout_7.addWidget(self.label_75, 2, 0, 1, 1)
        self.label_76 = QtGui.QLabel(self.groupBox_10)
        self.label_76.setObjectName("label_76")
        self.gridLayout_7.addWidget(self.label_76, 3, 0, 1, 1)
        self.horizontalLayout_33 = QtGui.QHBoxLayout()
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.spinBox_37 = QtGui.QSpinBox(self.groupBox_10)
        self.spinBox_37.setObjectName("spinBox_37")
        self.horizontalLayout_33.addWidget(self.spinBox_37)
        self.label_77 = QtGui.QLabel(self.groupBox_10)
        self.label_77.setObjectName("label_77")
        self.horizontalLayout_33.addWidget(self.label_77)
        self.spinBox_38 = QtGui.QSpinBox(self.groupBox_10)
        self.spinBox_38.setObjectName("spinBox_38")
        self.horizontalLayout_33.addWidget(self.spinBox_38)
        self.label_78 = QtGui.QLabel(self.groupBox_10)
        self.label_78.setObjectName("label_78")
        self.horizontalLayout_33.addWidget(self.label_78)
        self.gridLayout_7.addLayout(self.horizontalLayout_33, 2, 2, 1, 1)
        self.horizontalLayout_34 = QtGui.QHBoxLayout()
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.spinBox_39 = QtGui.QSpinBox(self.groupBox_10)
        self.spinBox_39.setObjectName("spinBox_39")
        self.horizontalLayout_34.addWidget(self.spinBox_39)
        self.label_79 = QtGui.QLabel(self.groupBox_10)
        self.label_79.setObjectName("label_79")
        self.horizontalLayout_34.addWidget(self.label_79)
        self.spinBox_40 = QtGui.QSpinBox(self.groupBox_10)
        self.spinBox_40.setObjectName("spinBox_40")
        self.horizontalLayout_34.addWidget(self.spinBox_40)
        self.label_80 = QtGui.QLabel(self.groupBox_10)
        self.label_80.setObjectName("label_80")
        self.horizontalLayout_34.addWidget(self.label_80)
        self.gridLayout_7.addLayout(self.horizontalLayout_34, 0, 2, 1, 1)
        self.horizontalLayout_35 = QtGui.QHBoxLayout()
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        self.spinBox_41 = QtGui.QSpinBox(self.groupBox_10)
        self.spinBox_41.setObjectName("spinBox_41")
        self.horizontalLayout_35.addWidget(self.spinBox_41)
        self.label_81 = QtGui.QLabel(self.groupBox_10)
        self.label_81.setObjectName("label_81")
        self.horizontalLayout_35.addWidget(self.label_81)
        self.spinBox_42 = QtGui.QSpinBox(self.groupBox_10)
        self.spinBox_42.setObjectName("spinBox_42")
        self.horizontalLayout_35.addWidget(self.spinBox_42)
        self.label_82 = QtGui.QLabel(self.groupBox_10)
        self.label_82.setObjectName("label_82")
        self.horizontalLayout_35.addWidget(self.label_82)
        self.gridLayout_7.addLayout(self.horizontalLayout_35, 1, 2, 1, 1)
        self.horizontalLayout_36 = QtGui.QHBoxLayout()
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")
        self.spinBox_43 = QtGui.QSpinBox(self.groupBox_10)
        self.spinBox_43.setReadOnly(True)
        self.spinBox_43.setObjectName("spinBox_43")
        self.horizontalLayout_36.addWidget(self.spinBox_43)
        self.label_83 = QtGui.QLabel(self.groupBox_10)
        self.label_83.setObjectName("label_83")
        self.horizontalLayout_36.addWidget(self.label_83)
        self.spinBox_44 = QtGui.QSpinBox(self.groupBox_10)
        self.spinBox_44.setObjectName("spinBox_44")
        self.horizontalLayout_36.addWidget(self.spinBox_44)
        self.label_84 = QtGui.QLabel(self.groupBox_10)
        self.label_84.setObjectName("label_84")
        self.horizontalLayout_36.addWidget(self.label_84)
        self.gridLayout_7.addLayout(self.horizontalLayout_36, 3, 2, 1, 1)
        self.gridLayout_11.addWidget(self.groupBox_10, 0, 1, 1, 1)
        self.stackedWidget.addWidget(self.CBED)
        self.verticalLayout_6.addWidget(self.stackedWidget)
        self.gridLayout_17.addLayout(self.verticalLayout_6, 0, 0, 1, 1)
        self.ProbeDock.setWidget(self.dockWidgetContents_4)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.ProbeDock)
        self.actionNew_Simulation = QtGui.QAction(MainWindow)
        self.actionNew_Simulation.setObjectName("actionNew_Simulation")
        self.actionLoad_Simulation = QtGui.QAction(MainWindow)
        self.actionLoad_Simulation.setObjectName("actionLoad_Simulation")
        self.actionAdvanced_Settings = QtGui.QAction(MainWindow)
        self.actionAdvanced_Settings.setObjectName("actionAdvanced_Settings")
        self.actionSave_Simulation = QtGui.QAction(MainWindow)
        self.actionSave_Simulation.setObjectName("actionSave_Simulation")
        self.actionAdvanced = QtGui.QAction(MainWindow)
        self.actionAdvanced.setObjectName("actionAdvanced")
        self.actionDefaults = QtGui.QAction(MainWindow)
        self.actionDefaults.setObjectName("actionDefaults")
        self.menuFile.addAction(self.actionNew_Simulation)
        self.menuFile.addAction(self.actionSave_Simulation)
        self.menuFile.addAction(self.actionLoad_Simulation)
        self.menuSettings.addAction(self.actionDefaults)
        self.menuSettings.addAction(self.actionAdvanced)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuResults.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.comboBox, QtCore.SIGNAL("currentIndexChanged(int)"), self.stackedWidget.setCurrentIndex)
        QtCore.QObject.connect(self.TDSCheck, QtCore.SIGNAL("toggled(bool)"), self.TDSRuns.setEnabled)
        QtCore.QObject.connect(self.FrontViewRadio, QtCore.SIGNAL("toggled(bool)"), self.groupBox_2.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.ModelView.setTitle(QtGui.QApplication.translate("MainWindow", "Model:", None, QtGui.QApplication.UnicodeUTF8))
        self.LoadModel.setText(QtGui.QApplication.translate("MainWindow", "Load Model", None, QtGui.QApplication.UnicodeUTF8))
        self.EditModel.setText(QtGui.QApplication.translate("MainWindow", "Edit Model", None, QtGui.QApplication.UnicodeUTF8))
        self.ModelParams.setText(QtGui.QApplication.translate("MainWindow", "Model Properties", None, QtGui.QApplication.UnicodeUTF8))
        self.ViewingFace.setTitle(QtGui.QApplication.translate("MainWindow", "Viewing face", None, QtGui.QApplication.UnicodeUTF8))
        self.TopViewRadio.setText(QtGui.QApplication.translate("MainWindow", "Top", None, QtGui.QApplication.UnicodeUTF8))
        self.FrontViewRadio.setText(QtGui.QApplication.translate("MainWindow", "Front (Depth)", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "Depth view mode", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_6.setText(QtGui.QApplication.translate("MainWindow", "Unit Cells", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_7.setText(QtGui.QApplication.translate("MainWindow", "Slab", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_8.setText(QtGui.QApplication.translate("MainWindow", "Super cell", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_6.setTitle(QtGui.QApplication.translate("MainWindow", "Model Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.BoxSizeRadio_2.setText(QtGui.QApplication.translate("MainWindow", "BoxSize", None, QtGui.QApplication.UnicodeUTF8))
        self.NCellsRadio_2.setText(QtGui.QApplication.translate("MainWindow", "NCells", None, QtGui.QApplication.UnicodeUTF8))
        self.label_95.setText(QtGui.QApplication.translate("MainWindow", "Unit Cells:", None, QtGui.QApplication.UnicodeUTF8))
        self.SizeXLabel_2.setText(QtGui.QApplication.translate("MainWindow", "Nx", None, QtGui.QApplication.UnicodeUTF8))
        self.SizeZLabel_2.setText(QtGui.QApplication.translate("MainWindow", "Nz", None, QtGui.QApplication.UnicodeUTF8))
        self.SizeYLabel_2.setText(QtGui.QApplication.translate("MainWindow", "Ny", None, QtGui.QApplication.UnicodeUTF8))
        self.label_97.setText(QtGui.QApplication.translate("MainWindow", "Sample Tilt:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_99.setText(QtGui.QApplication.translate("MainWindow", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.label_98.setText(QtGui.QApplication.translate("MainWindow", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.label_96.setText(QtGui.QApplication.translate("MainWindow", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.SampleTiltDegreesRadio_2.setText(QtGui.QApplication.translate("MainWindow", "Degrees", None, QtGui.QApplication.UnicodeUTF8))
        self.SampleTiltRadiansRadio_2.setText(QtGui.QApplication.translate("MainWindow", "Radians", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuResults.setTitle(QtGui.QApplication.translate("MainWindow", "Results", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSettings.setTitle(QtGui.QApplication.translate("MainWindow", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.SlabDock.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Slab Configuration", None, QtGui.QApplication.UnicodeUTF8))
        self.label_86.setText(QtGui.QApplication.translate("MainWindow", "Number of Sub-slabs:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Potential Offset:  X", None, QtGui.QApplication.UnicodeUTF8))
        self.label_85.setText(QtGui.QApplication.translate("MainWindow", "Slice Thickness", None, QtGui.QApplication.UnicodeUTF8))
        self.label_87.setText(QtGui.QApplication.translate("MainWindow", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Slices per slab:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_88.setText(QtGui.QApplication.translate("MainWindow", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_3.setText(QtGui.QApplication.translate("MainWindow", "Center Slices", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_4.setText(QtGui.QApplication.translate("MainWindow", "Periodic X,Y", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_5.setText(QtGui.QApplication.translate("MainWindow", "Periodic Z", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_7.setText(QtGui.QApplication.translate("MainWindow", "Auto Z", None, QtGui.QApplication.UnicodeUTF8))
        self.DetectorsDock.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Detectors", None, QtGui.QApplication.UnicodeUTF8))
        self.label_89.setText(QtGui.QApplication.translate("MainWindow", "Collection Angles:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_94.setText(QtGui.QApplication.translate("MainWindow", "Inner", None, QtGui.QApplication.UnicodeUTF8))
        self.label_93.setText(QtGui.QApplication.translate("MainWindow", "Outer", None, QtGui.QApplication.UnicodeUTF8))
        self.label_90.setText(QtGui.QApplication.translate("MainWindow", "Detector Offset:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_91.setText(QtGui.QApplication.translate("MainWindow", "X: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_92.setText(QtGui.QApplication.translate("MainWindow", "Y: ", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_8.setText(QtGui.QApplication.translate("MainWindow", "Rename Detector", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_9.setText(QtGui.QApplication.translate("MainWindow", "Delete Detector", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Detector1), QtGui.QApplication.translate("MainWindow", "Detector 1", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "Add Detector...", None, QtGui.QApplication.UnicodeUTF8))
        self.MicroscopeDock.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Microscope", None, QtGui.QApplication.UnicodeUTF8))
        self.MicroscopeConfig.setTitle(QtGui.QApplication.translate("MainWindow", "Microscope Parameters:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_33.setText(QtGui.QApplication.translate("MainWindow", "High Voltage:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_34.setText(QtGui.QApplication.translate("MainWindow", "Defocus:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_35.setText(QtGui.QApplication.translate("MainWindow", "Astigmatism:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_36.setText(QtGui.QApplication.translate("MainWindow", "Spherical Aberr. C3:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_37.setText(QtGui.QApplication.translate("MainWindow", "Temperature:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_38.setText(QtGui.QApplication.translate("MainWindow", "Chromatic Aberr. Cc:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_39.setText(QtGui.QApplication.translate("MainWindow", "Convergence Angle:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_40.setText(QtGui.QApplication.translate("MainWindow", "Beam Tilt:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_41.setText(QtGui.QApplication.translate("MainWindow", "kV", None, QtGui.QApplication.UnicodeUTF8))
        self.label_42.setText(QtGui.QApplication.translate("MainWindow", "nm", None, QtGui.QApplication.UnicodeUTF8))
        self.label_43.setText(QtGui.QApplication.translate("MainWindow", "nm", None, QtGui.QApplication.UnicodeUTF8))
        self.label_44.setText(QtGui.QApplication.translate("MainWindow", "mm", None, QtGui.QApplication.UnicodeUTF8))
        self.label_45.setText(QtGui.QApplication.translate("MainWindow", "k", None, QtGui.QApplication.UnicodeUTF8))
        self.label_46.setText(QtGui.QApplication.translate("MainWindow", "mm", None, QtGui.QApplication.UnicodeUTF8))
        self.label_47.setText(QtGui.QApplication.translate("MainWindow", "mrad", None, QtGui.QApplication.UnicodeUTF8))
        self.label_48.setText(QtGui.QApplication.translate("MainWindow", "A/cm2sr", None, QtGui.QApplication.UnicodeUTF8))
        self.label_49.setText(QtGui.QApplication.translate("MainWindow", "Brightness (x10^8):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_50.setText(QtGui.QApplication.translate("MainWindow", "Dwell Time:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_51.setText(QtGui.QApplication.translate("MainWindow", "us", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_5.setText(QtGui.QApplication.translate("MainWindow", "Set Scherzer Defocus", None, QtGui.QApplication.UnicodeUTF8))
        self.label_52.setText(QtGui.QApplication.translate("MainWindow", "Angle:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_53.setText(QtGui.QApplication.translate("MainWindow", "Units", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_6.setText(QtGui.QApplication.translate("MainWindow", "Higher Order Aberrations", None, QtGui.QApplication.UnicodeUTF8))
        self.TDSCheck.setText(QtGui.QApplication.translate("MainWindow", "TDS", None, QtGui.QApplication.UnicodeUTF8))
        self.label_54.setText(QtGui.QApplication.translate("MainWindow", "Runs:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_55.setText(QtGui.QApplication.translate("MainWindow", "dE:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_56.setText(QtGui.QApplication.translate("MainWindow", "eV", None, QtGui.QApplication.UnicodeUTF8))
        self.label_57.setText(QtGui.QApplication.translate("MainWindow", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.label_58.setText(QtGui.QApplication.translate("MainWindow", "Units", None, QtGui.QApplication.UnicodeUTF8))
        self.label_59.setText(QtGui.QApplication.translate("MainWindow", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.label_60.setText(QtGui.QApplication.translate("MainWindow", "Units", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_2.setText(QtGui.QApplication.translate("MainWindow", "Tilt back", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_2.setItemText(0, QtGui.QApplication.translate("MainWindow", "Microscope Presets...", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_2.setItemText(1, QtGui.QApplication.translate("MainWindow", "NION UltraSTEM 100 @100kV", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_2.setItemText(2, QtGui.QApplication.translate("MainWindow", "JEOL 2100 @200kV, Cs (probe) corrector", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_2.setItemText(3, QtGui.QApplication.translate("MainWindow", "FEI Titan @300kV, Cs (probe) corrector", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_2.setItemText(4, QtGui.QApplication.translate("MainWindow", "Save current settings as preset...", None, QtGui.QApplication.UnicodeUTF8))
        self.ProbeDock.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Probe/Scan", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Simulation Mode:", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "STEM", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "TEM", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(2, QtGui.QApplication.translate("MainWindow", "Coherent CBED", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Scanning Window", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "X Start:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Pixels", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "Y Start:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("MainWindow", "Pixels", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("MainWindow", "Probe Array:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("MainWindow", "Array Size:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("MainWindow", "Resolution:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("MainWindow", "Window Size:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setText(QtGui.QApplication.translate("MainWindow", "Scattering Angle:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("MainWindow", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setText(QtGui.QApplication.translate("MainWindow", "A", None, QtGui.QApplication.UnicodeUTF8))
        self.label_61.setText(QtGui.QApplication.translate("MainWindow", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.label_62.setText(QtGui.QApplication.translate("MainWindow", "Pixels", None, QtGui.QApplication.UnicodeUTF8))
        self.label_63.setText(QtGui.QApplication.translate("MainWindow", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.label_64.setText(QtGui.QApplication.translate("MainWindow", "A", None, QtGui.QApplication.UnicodeUTF8))
        self.label_65.setText(QtGui.QApplication.translate("MainWindow", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.label_66.setText(QtGui.QApplication.translate("MainWindow", "mrad", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_9.setTitle(QtGui.QApplication.translate("MainWindow", "Wavefunction Array:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("MainWindow", "Array Size:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("MainWindow", "Resolution:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_31.setText(QtGui.QApplication.translate("MainWindow", "Window Size:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_32.setText(QtGui.QApplication.translate("MainWindow", "Scattering Angle:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_67.setText(QtGui.QApplication.translate("MainWindow", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.label_68.setText(QtGui.QApplication.translate("MainWindow", "A", None, QtGui.QApplication.UnicodeUTF8))
        self.label_69.setText(QtGui.QApplication.translate("MainWindow", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.label_70.setText(QtGui.QApplication.translate("MainWindow", "Pixels", None, QtGui.QApplication.UnicodeUTF8))
        self.label_71.setText(QtGui.QApplication.translate("MainWindow", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.label_72.setText(QtGui.QApplication.translate("MainWindow", "A", None, QtGui.QApplication.UnicodeUTF8))
        self.label_73.setText(QtGui.QApplication.translate("MainWindow", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.label_74.setText(QtGui.QApplication.translate("MainWindow", "mrad", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_4.setText(QtGui.QApplication.translate("MainWindow", "Simulate Images from Wavefunction", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_8.setTitle(QtGui.QApplication.translate("MainWindow", "Probe Position", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("MainWindow", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("MainWindow", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_10.setTitle(QtGui.QApplication.translate("MainWindow", "Probe Array:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("MainWindow", "Array Size:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("MainWindow", "Resolution:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_75.setText(QtGui.QApplication.translate("MainWindow", "Window Size:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_76.setText(QtGui.QApplication.translate("MainWindow", "Scattering Angle:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_77.setText(QtGui.QApplication.translate("MainWindow", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.label_78.setText(QtGui.QApplication.translate("MainWindow", "A", None, QtGui.QApplication.UnicodeUTF8))
        self.label_79.setText(QtGui.QApplication.translate("MainWindow", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.label_80.setText(QtGui.QApplication.translate("MainWindow", "Pixels", None, QtGui.QApplication.UnicodeUTF8))
        self.label_81.setText(QtGui.QApplication.translate("MainWindow", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.label_82.setText(QtGui.QApplication.translate("MainWindow", "A", None, QtGui.QApplication.UnicodeUTF8))
        self.label_83.setText(QtGui.QApplication.translate("MainWindow", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.label_84.setText(QtGui.QApplication.translate("MainWindow", "mrad", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew_Simulation.setText(QtGui.QApplication.translate("MainWindow", "New Simulation", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoad_Simulation.setText(QtGui.QApplication.translate("MainWindow", "Load Simulation", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAdvanced_Settings.setText(QtGui.QApplication.translate("MainWindow", "Advanced Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_Simulation.setText(QtGui.QApplication.translate("MainWindow", "Save Simulation", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAdvanced.setText(QtGui.QApplication.translate("MainWindow", "Advanced", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDefaults.setText(QtGui.QApplication.translate("MainWindow", "Defaults", None, QtGui.QApplication.UnicodeUTF8))

